#!/bin/bash
echo "LOG_LEVEL: $LOG_LEVEL"
echo "MODE: $MODE"
echo "KEEP_AWAKE: $KEEP_AWAKE"
echo "HUB_ALWAYS_ON: $HUB_ALWAYS_ON"
echo "SKIP_MAINTENANCE: $SKIP_MAINTENANCE"
echo "IGNORE_LOW_VOLTAGE: $IGNORE_LOW_VOLTAGE"
