name: amigos-test-env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=2.7*
  - codecov=2.0*
  - flake8=3.7*
  - pytest=4.6*
  - pytest-cov=2.7*
  - pytest-mock=1.11*
  - pyfakefs=3.6*
  - pyserial=3.4*
