from honcho.tasks import aquadopp  # noqa
from honcho.tasks import binex  # noqa
from honcho.tasks import camera  # noqa
from honcho.tasks import cr1000x  # noqa
from honcho.tasks import dts  # noqa
from honcho.tasks import monitor  # noqa
from honcho.tasks import onboard  # noqa
from honcho.tasks import orders  # noqa
from honcho.tasks import sbd  # noqa
from honcho.tasks import seabird  # noqa
from honcho.tasks import solar  # noqa
from honcho.tasks import upload  # noqa
from honcho.tasks import vaisala  # noqa
