from PIL import Image
foo = Image.open("/home/coovi/Downloads/file_2019-07-25 18:26:56.517321.jpg")
# print (foo.histogram())
print(foo.size)
# foo = foo.resize((160, 300), Image.ANTIALIAS)
# print(foo.size)
foo.save("/home/coovi/Downloads/file.png", dpi=(400, 400), quality=50)
foo = Image.open("/home/coovi/Downloads/file.png")
# print (foo.histogram())
print(foo.size)
