#!/bin/bash
i="0"
#Watchdog set
echo 3 >/sys/class/gpio/wdt_ctl/data
sleep 1
echo 0 >/sys/class/gpio/wdt_ctl/data
sleep 1
echo 3 >/sys/class/gpio/wdt_ctl/data

while [ $i -le 3 ]; do
    if ps | grep amigos.py | grep -v -q grep; then

        echo "none" >/dev/null

    else
        export LD_LIBRARY_PATH=/media/mmcblk0p1/codes/thumb/
        sleep 1
        time_now="$(date)"
        echo "${time_now:0:19} ${time_now:24}: Restarting Scheduler" >>/media/mmcblk0p1/logs/system.log
        python /media/mmcblk0p1/codes/amigos.py &
        sleep 1
        # power up the router
        # amigos power -m_on &
        echo 1 >/sys/class/gpio/pwr_ctl/index
        sleep 1
        echo 0x08 >/sys/class/gpio/pwr_ctl/data
        sleep 15
    fi
    i=$(($i + 1))
done

#cp -r /var/volatile/log/ /media/mmcblk0p1/logs/
#dmesg > /media/mmcblk0p1/logs/dmesg.log

last_run="$(date -r /media/mmcblk0p1/logs/system.log +%s)"
time_now="$(date +%s)"

diff=$((time_now - last_run))
if (($diff > 3600)); then
    pidd="$(pgrep python)"
    echo "${time_now:0:19} ${time_now:24}: Scheduler freezed" >>/media/mmcblk0p1/logs/system.log
    kill -9 $pidd
fi
