#!/bin/sh
# /mnt/gpio/rs232_ON
# /mnt/gpio/iridium_ON
# sleep 1
# /mnt/gpio/ip6600_ON
# sleep 1
# /mnt/gpio/hub_ON
# sleep 10

# ifconfig eth0 up
# sleep 1
# ifconfig eth0 up
# route add default gw 192.168.0.1

BODIES=("ppp1_local_ip=192.168.0.1&ppp1_remote_ip=192.168.0.90&ppp1_override_remote_ip=enable" "form=form_activate_config")
for BODY in ${BODIES[@]}; do
   BODY_LEN=$(echo -n ${BODY} | wc -c)
   echo $BODY_LEN
   printf "POST /cgi-bin/menuform.cgi HTTP/1.1\r\nUser-Agent: nc/0.0.1\r\nHost: 192.168.0.1:8080\r\nAuthorization: Basic aXA2NjAwOmFtaWdvczEy\r\nAccept: */*\r\nContent-Length: ${BODY_LEN}\r\nContent-Type: application/x-www-form-encoded\r\n\r\n${BODY}" | nc 192.168.0.1 8080 >/dev/null 2>&1
done
