#!/bin/bash
DIR=/media/mmcblk0p1
BACKUPS="${DIR}/backups"
DTS="${DIR}/backups/dts"
GPS="${DIR}/backups/gps"
WEATHER="${DIR}/backups/weather"
SOLAR="${DIR}/backups/solar"
CR1000X="${DIR}/backups/cr1000x"
PICTURES="${DIR}/pictures"
LOGS="${DIR}/logs"
POWER="${DIR}/logs"
SYSTEM="${DIR}/logs/system.log"
#BLACK_HOLE= /dev/null

if [ ! -d $DIR ]; then
    echo "This code can not run on this computer. Are  sure you are on a Tritron board?"
    echo "If so, check If SD_CARD directory In /media is named mmcblk0p1."
    echo "In case the name is different, let the sotware enginieurs know. Thanks"
    echo "Contact:"
    echo "  Coovi M"
    echo "      Email: coovi.meha@colorado.edu"
    echo "      Phone: 720-468-9447"
    echo "  Bruce W: "
    echo "      Email: coovi.meha@colorado.edu"
    echo "      Phone: 720-468-9447"
    echo "  Sid A"
    echo "      Email: coovi.meha@colorado.edu"
    echo "      Phone: 720-468-9447"
    exit
fi

if [ ! -d $LOGS ]; then
    cd $DIR && mkdir logs && cd $LOGS && touch power_log.log && echo "0b00000000,0b00000000,0b00000000" >logs/power_log.log

else
    if [ ! test power_log.log ]; then
        cd $DIR && cd $LOGS && touch power_log.log && echo "0b00000000,0b00000000,0b00000000" >logs/power_log.log
    else
        cd $DIR && cd $LOGS && echo "0b00000000,0b00000000,0b00000000" >logs/power_log.log
    fi
fi

time_now="$(date)"
echo "${time_now:0:19} ${time_now:24}: Checking For missing folder and creating them!" >$SYSTEM

if [ ! -d $PICTURES ]; then
    cd $DIR && mkdir pictures
fi

if [ ! -d $BACKUPS ]; then
    cd $DIR && mkdir backups
else
    if [ ! -d $GPS ]; then
        cd $BACKUPS && mkdir gps
    fi

    if [ ! -d $DTS ]; then
        cd $BACKUPS && mkdir dts
    fi

    if [ ! -d $WEATHER ]; then
        cd $BACKUPS && mkdir weather
    fi

    if [ ! -d $SOLAR ]; then
        cd $BACKUPS && mkdir solar
    fi

    if [ ! -d $CR1000X ]; then
        cd $BACKUPS && mkdir CR1000x
    fi

fi

time_now="$(date)"
echo "${time_now:0:19} ${time_now:24}: All required folders and files created!" >$SYSTEM
