#!/bin/bash
DIR=/media/mmcblk0p1
BACKUPS="${DIR}/backups"
BACKDTS="${DIR}/backups/dts"
BACKSYS="${DIR}/backups/system"
DTS="${DIR}/dts"
GPS="${DIR}/backups/gps"
WEATHER="${DIR}/backups/weather"
SOLAR="${DIR}/backups/solar"
CR1000X="${DIR}/backups/cr1000x"
PICTURES="${DIR}/pictures"
UPICTURES="${DIR}/unscaled_pictures"
LOGS="${DIR}/logs"
POWER="${DIR}/logs/power_log.log"
SLEPT="${DIR}/logs/slept.log"
SYSTEM="${DIR}/logs/system.log"
BACK_PHOTO="${DIR}/backups/pictures"
#BLACK_HOLE= /dev/null

time_now="$(date)"

if [ ! -d $DIR ]; then
    echo "This code can not run on this computer. Are  sure you are on a Tritron board?"
    echo "If so, check If SD_CARD directory In /media is named mmcblk0p1 by typing 'cd /media && ls'"
    echo "In case the name is different, let the software engineers know. Thanks"
    echo " "
    echo "Contact:"
    echo "  Coovi M"
    echo "      Email: coovi.meha@colorado.edu"
    echo "      Phone: 720-468-9447"
    echo "  Bruce W: "
    echo "      Email: coovi.meha@colorado.edu"
    echo "      Phone: 720-468-9447"
    echo "  Sid A"
    echo "      Email: siar7178@colorado.edu"
    echo "      Phone: 720-839-2887"
    exit 0
fi

if [ ! -d $LOGS ]; then
    mkdir $LOGS && touch $POWER && echo "0b00000000,0b00000000,0b00000000" >$POWER
    echo "${time_now:0:19} ${time_now:24}: Logs folder missing! Created" >>$SYSTEM
else
    if [ ! -f $POWER ]; then
        touch $POWER && echo "0b00000000,0b0000000,0b00000000" >$POWER
        echo "${time_now:0:19} ${time_now:24}: Power track file missing! Created" >>$SYSTEM
    else
        if [ -s $POWER ]; then
            echo "not empty" >/dev/null
        else
            echo "0b00000000,0b00000000,0b00000000" >$POWER
            echo "${time_now:0:19} ${time_now:24}: Power track file empty! Filled" >>$SYSTEM
        fi
    fi
fi

if [ ! -f $SLEPT ]; then
    touch $SLEPT
fi

if [ ! -d $PICTURES ]; then
    mkdir $PICTURES
    echo "${time_now:0:19} ${time_now:24}: Pictures folder missing! Created" >>$SYSTEM
fi
if [ ! -d $UPICTURES ]; then
    mkdir $UPICTURES
    echo "${time_now:0:19} ${time_now:24}: Unscaled pictures folder missing! Created" >>$SYSTEM
fi
if [ ! -d $BACKUPS ]; then
    mkdir $BACKUPS
    echo "${time_now:0:19} ${time_now:24}: Backups folder missing! Creating all ..." >>$SYSTEM
fi
if [ ! -d $GPS ]; then
    mkdir $GPS
fi
if [ ! -d $BACKSYS ]; then
    mkdir $BACKSYS
fi
if [ ! -d $DTS ]; then
    mkdir $DTS
fi

if [ ! -d $BACKDTS ]; then
    mkdir $BACKDTS
fi

if [ ! -d $WEATHER ]; then
    mkdir $WEATHER
fi

if [ ! -d $SOLAR ]; then
    mkdir $SOLAR
fi

if [ ! -d $CR1000X ]; then
    mkdir $CR1000X
fi

if [ ! -d $BACK_PHOTO ]; then
    mkdir $BACK_PHOTO
fi
